LANGUAGES = {
    'ru': {
        'title': 'QR-код генератор',
        'enter_text': 'Введите текст',
        'generate': 'Сгенерировать',
        'paste': 'Вставить',
        'menu_file': 'Файл',
        'menu_save': 'Сохранить',
        'menu_exit': 'Выход',
        'menu_settings': 'Настройки',
        'menu_language': 'Язык',
        'colors': 'Цвета',
        'qr_color': 'Цвет QR-кода',
        'bg_color': 'Цвет фона',
        'qr_color_title': 'Выберите цвет QR-кода',
        'bg_color_title': 'Выберите цвет фона',
        'black_white': 'Черный на белом',
        'blue_white': 'Синий на белом',
        'red_white': 'Красный на белом',
        'green_white': 'Зеленый на белом',
        'logo': 'Логотип',
        'add_logo': 'Добавить логотип',
        'remove_logo': 'Удалить логотип',
        'type': 'Тип QR-кода',
        'type_text': 'Текст',
        'type_wifi': 'Wi-Fi',
        'type_location': 'Геолокация',
        'temp_qr': 'Временный QR-код',
        'temp_1h': 'На 1 час',
        'temp_24h': 'На 24 часа',
        'temp_7d': 'На 7 дней',
        'history': 'История',
        'show_history': 'Показать историю',
        'clear_history': 'Очистить историю',
        'encryption': 'Шифрование',
        'encrypt_qr': 'Зашифровать QR-код',
        'decrypt_qr': 'Расшифровать QR-код',
        'warning': 'Предупреждение',
        'success': 'Успех',
        'info': 'Информация',
        'yes': 'Да',
        'no': 'Нет',
        'enter_password': 'Введите пароль',
        'encrypt_title': 'Шифрование QR-кода',
        'encrypt_password': 'Введите пароль для шифрования',
        'encrypt_success': 'QR-код успешно зашифрован',
        'decrypt_title': 'Расшифровка QR-кода',
        'decrypt_password': 'Введите пароль для расшифровки',
        'decrypt_success': 'QR-код успешно расшифрован',
        'temp_qr_info': 'QR-код будет действителен {minutes} минут',
        'history_title': 'История QR-кодов',
        'history_text': 'Текст',
        'history_type': 'Тип',
        'history_created': 'Создан',
        'history_expires': 'Истекает',
        'history_encrypted': 'Зашифрован',
        'history_permanent': 'Постоянный',
        'history_clear_confirm': 'Вы уверены, что хотите очистить историю?',
        'history_cleared': 'История очищена',
        'wifi_title': 'Wi-Fi QR-код',
        'wifi_ssid': 'Имя сети (SSID)',
        'wifi_password': 'Пароль',
        'wifi_error': 'Введите имя сети и пароль',
        'location_title': 'Геолокация QR-код',
        'location_lat': 'Широта',
        'location_lon': 'Долгота',
        'location_error': 'Введите корректные координаты'
    },
    'en': {
        'title': 'QR Code Generator',
        'enter_text': 'Enter text',
        'generate': 'Generate',
        'paste': 'Paste',
        'menu_file': 'File',
        'menu_save': 'Save',
        'menu_exit': 'Exit',
        'menu_settings': 'Settings',
        'menu_language': 'Language',
        'colors': 'Colors',
        'qr_color': 'QR Code Color',
        'bg_color': 'Background Color',
        'qr_color_title': 'Choose QR Code Color',
        'bg_color_title': 'Choose Background Color',
        'black_white': 'Black on White',
        'blue_white': 'Blue on White',
        'red_white': 'Red on White',
        'green_white': 'Green on White',
        'logo': 'Logo',
        'add_logo': 'Add Logo',
        'remove_logo': 'Remove Logo',
        'type': 'QR Code Type',
        'type_text': 'Text',
        'type_wifi': 'Wi-Fi',
        'type_location': 'Location',
        'temp_qr': 'Temporary QR Code',
        'temp_1h': '1 Hour',
        'temp_24h': '24 Hours',
        'temp_7d': '7 Days',
        'history': 'History',
        'show_history': 'Show History',
        'clear_history': 'Clear History',
        'encryption': 'Encryption',
        'encrypt_qr': 'Encrypt QR Code',
        'decrypt_qr': 'Decrypt QR Code',
        'warning': 'Warning',
        'success': 'Success',
        'info': 'Information',
        'yes': 'Yes',
        'no': 'No',
        'enter_password': 'Enter password',
        'encrypt_title': 'Encrypt QR Code',
        'encrypt_password': 'Enter encryption password',
        'encrypt_success': 'QR code successfully encrypted',
        'decrypt_title': 'Decrypt QR Code',
        'decrypt_password': 'Enter decryption password',
        'decrypt_success': 'QR code successfully decrypted',
        'temp_qr_info': 'QR code will be valid for {minutes} minutes',
        'history_title': 'QR Code History',
        'history_text': 'Text',
        'history_type': 'Type',
        'history_created': 'Created',
        'history_expires': 'Expires',
        'history_encrypted': 'Encrypted',
        'history_permanent': 'Permanent',
        'history_clear_confirm': 'Are you sure you want to clear history?',
        'history_cleared': 'History cleared',
        'wifi_title': 'Wi-Fi QR Code',
        'wifi_ssid': 'Network Name (SSID)',
        'wifi_password': 'Password',
        'wifi_error': 'Enter network name and password',
        'location_title': 'Location QR Code',
        'location_lat': 'Latitude',
        'location_lon': 'Longitude',
        'location_error': 'Enter valid coordinates'
    },
    'es': {
        'title': 'Generador de Códigos QR',
        'enter_text': 'Ingrese texto',
        'generate': 'Generar',
        'paste': 'Pegar',
        'menu_file': 'Archivo',
        'menu_save': 'Guardar',
        'menu_exit': 'Salir',
        'menu_settings': 'Configuración',
        'menu_language': 'Idioma',
        'colors': 'Colores',
        'qr_color': 'Color del código QR',
        'bg_color': 'Color de fondo',
        'qr_color_title': 'Elija el color del código QR',
        'bg_color_title': 'Elija el color de fondo',
        'black_white': 'Negro sobre blanco',
        'blue_white': 'Azul sobre blanco',
        'red_white': 'Rojo sobre blanco',
        'green_white': 'Verde sobre blanco',
        'logo': 'Logo',
        'add_logo': 'Añadir logo',
        'remove_logo': 'Eliminar logo',
        'type': 'Tipo de código QR',
        'type_text': 'Texto',
        'type_wifi': 'Wi-Fi',
        'type_location': 'Ubicación',
        'temp_qr': 'Código QR temporal',
        'temp_1h': '1 hora',
        'temp_24h': '24 horas',
        'temp_7d': '7 días',
        'history': 'Historial',
        'show_history': 'Mostrar historial',
        'clear_history': 'Limpiar historial',
        'encryption': 'Cifrado',
        'encrypt_qr': 'Cifrar código QR',
        'decrypt_qr': 'Descifrar código QR',
        'warning': 'Advertencia',
        'success': 'Éxito',
        'info': 'Información',
        'yes': 'Sí',
        'no': 'No',
        'enter_password': 'Ingrese contraseña',
        'encrypt_title': 'Cifrar código QR',
        'encrypt_password': 'Ingrese contraseña para cifrar',
        'encrypt_success': 'Código QR cifrado exitosamente',
        'decrypt_title': 'Descifrar código QR',
        'decrypt_password': 'Ingrese contraseña para descifrar',
        'decrypt_success': 'Código QR descifrado exitosamente',
        'temp_qr_info': 'El código QR será válido por {minutes} minutos',
        'history_title': 'Historial de códigos QR',
        'history_text': 'Texto',
        'history_type': 'Tipo',
        'history_created': 'Creado',
        'history_expires': 'Expira',
        'history_encrypted': 'Cifrado',
        'history_permanent': 'Permanente',
        'history_clear_confirm': '¿Está seguro de que desea limpiar el historial?',
        'history_cleared': 'Historial limpiado',
        'wifi_title': 'Código QR Wi-Fi',
        'wifi_ssid': 'Nombre de red (SSID)',
        'wifi_password': 'Contraseña',
        'wifi_error': 'Ingrese nombre de red y contraseña',
        'location_title': 'Código QR de ubicación',
        'location_lat': 'Latitud',
        'location_lon': 'Longitud',
        'location_error': 'Ingrese coordenadas válidas'
    },
    'fr': {
        'title': 'Générateur de Codes QR',
        'enter_text': 'Entrez le texte',
        'generate': 'Générer',
        'paste': 'Coller',
        'menu_file': 'Fichier',
        'menu_save': 'Enregistrer',
        'menu_exit': 'Quitter',
        'menu_settings': 'Paramètres',
        'menu_language': 'Langue',
        'colors': 'Couleurs',
        'qr_color': 'Couleur du code QR',
        'bg_color': 'Couleur de fond',
        'qr_color_title': 'Choisissez la couleur du code QR',
        'bg_color_title': 'Choisissez la couleur de fond',
        'black_white': 'Noir sur blanc',
        'blue_white': 'Bleu sur blanc',
        'red_white': 'Rouge sur blanc',
        'green_white': 'Vert sur blanc',
        'logo': 'Logo',
        'add_logo': 'Ajouter un logo',
        'remove_logo': 'Supprimer le logo',
        'type': 'Type de code QR',
        'type_text': 'Texte',
        'type_wifi': 'Wi-Fi',
        'type_location': 'Localisation',
        'temp_qr': 'Code QR temporaire',
        'temp_1h': '1 heure',
        'temp_24h': '24 heures',
        'temp_7d': '7 jours',
        'history': 'Historique',
        'show_history': 'Afficher l\'historique',
        'clear_history': 'Effacer l\'historique',
        'encryption': 'Chiffrement',
        'encrypt_qr': 'Chiffrer le code QR',
        'decrypt_qr': 'Déchiffrer le code QR',
        'warning': 'Avertissement',
        'success': 'Succès',
        'info': 'Information',
        'yes': 'Oui',
        'no': 'Non',
        'enter_password': 'Entrez le mot de passe',
        'encrypt_title': 'Chiffrer le code QR',
        'encrypt_password': 'Entrez le mot de passe pour chiffrer',
        'encrypt_success': 'Code QR chiffré avec succès',
        'decrypt_title': 'Déchiffrer le code QR',
        'decrypt_password': 'Entrez le mot de passe pour déchiffrer',
        'decrypt_success': 'Code QR déchiffré avec succès',
        'temp_qr_info': 'Le code QR sera valide pendant {minutes} minutes',
        'history_title': 'Historique des codes QR',
        'history_text': 'Texte',
        'history_type': 'Type',
        'history_created': 'Créé',
        'history_expires': 'Expire',
        'history_encrypted': 'Chiffré',
        'history_permanent': 'Permanent',
        'history_clear_confirm': 'Êtes-vous sûr de vouloir effacer l\'historique ?',
        'history_cleared': 'Historique effacé',
        'wifi_title': 'Code QR Wi-Fi',
        'wifi_ssid': 'Nom du réseau (SSID)',
        'wifi_password': 'Mot de passe',
        'wifi_error': 'Entrez le nom du réseau et le mot de passe',
        'location_title': 'Code QR de localisation',
        'location_lat': 'Latitude',
        'location_lon': 'Longitude',
        'location_error': 'Entrez des coordonnées valides'
    },
    'de': {
        'title': 'QR-Code Generator',
        'enter_text': 'Text eingeben',
        'generate': 'Generieren',
        'paste': 'Einfügen',
        'menu_file': 'Datei',
        'menu_save': 'Speichern',
        'menu_exit': 'Beenden',
        'menu_settings': 'Einstellungen',
        'menu_language': 'Sprache',
        'colors': 'Farben',
        'qr_color': 'QR-Code Farbe',
        'bg_color': 'Hintergrundfarbe',
        'qr_color_title': 'QR-Code Farbe wählen',
        'bg_color_title': 'Hintergrundfarbe wählen',
        'black_white': 'Schwarz auf Weiß',
        'blue_white': 'Blau auf Weiß',
        'red_white': 'Rot auf Weiß',
        'green_white': 'Grün auf Weiß',
        'logo': 'Logo',
        'add_logo': 'Logo hinzufügen',
        'remove_logo': 'Logo entfernen',
        'type': 'QR-Code Typ',
        'type_text': 'Text',
        'type_wifi': 'Wi-Fi',
        'type_location': 'Standort',
        'temp_qr': 'Temporärer QR-Code',
        'temp_1h': '1 Stunde',
        'temp_24h': '24 Stunden',
        'temp_7d': '7 Tage',
        'history': 'Verlauf',
        'show_history': 'Verlauf anzeigen',
        'clear_history': 'Verlauf löschen',
        'encryption': 'Verschlüsselung',
        'encrypt_qr': 'QR-Code verschlüsseln',
        'decrypt_qr': 'QR-Code entschlüsseln',
        'warning': 'Warnung',
        'success': 'Erfolg',
        'info': 'Information',
        'yes': 'Ja',
        'no': 'Nein',
        'enter_password': 'Passwort eingeben',
        'encrypt_title': 'QR-Code verschlüsseln',
        'encrypt_password': 'Passwort zum Verschlüsseln eingeben',
        'encrypt_success': 'QR-Code erfolgreich verschlüsselt',
        'decrypt_title': 'QR-Code entschlüsseln',
        'decrypt_password': 'Passwort zum Entschlüsseln eingeben',
        'decrypt_success': 'QR-Code erfolgreich entschlüsselt',
        'temp_qr_info': 'QR-Code ist {minutes} Minuten gültig',
        'history_title': 'QR-Code Verlauf',
        'history_text': 'Text',
        'history_type': 'Typ',
        'history_created': 'Erstellt',
        'history_expires': 'Läuft ab',
        'history_encrypted': 'Verschlüsselt',
        'history_permanent': 'Permanent',
        'history_clear_confirm': 'Möchten Sie den Verlauf wirklich löschen?',
        'history_cleared': 'Verlauf gelöscht',
        'wifi_title': 'Wi-Fi QR-Code',
        'wifi_ssid': 'Netzwerkname (SSID)',
        'wifi_password': 'Passwort',
        'wifi_error': 'Netzwerkname und Passwort eingeben',
        'location_title': 'Standort QR-Code',
        'location_lat': 'Breitengrad',
        'location_lon': 'Längengrad',
        'location_error': 'Gültige Koordinaten eingeben'
    },
    'zh': {
        'title': '二维码生成器',
        'enter_text': '输入文本',
        'generate': '生成',
        'paste': '粘贴',
        'menu_file': '文件',
        'menu_save': '保存',
        'menu_exit': '退出',
        'menu_settings': '设置',
        'menu_language': '语言',
        'colors': '颜色',
        'qr_color': '二维码颜色',
        'bg_color': '背景颜色',
        'qr_color_title': '选择二维码颜色',
        'bg_color_title': '选择背景颜色',
        'black_white': '黑底白字',
        'blue_white': '蓝底白字',
        'red_white': '红底白字',
        'green_white': '绿底白字',
        'logo': '标志',
        'add_logo': '添加标志',
        'remove_logo': '删除标志',
        'type': '二维码类型',
        'type_text': '文本',
        'type_wifi': 'Wi-Fi',
        'type_location': '位置',
        'temp_qr': '临时二维码',
        'temp_1h': '1小时',
        'temp_24h': '24小时',
        'temp_7d': '7天',
        'history': '历史记录',
        'show_history': '显示历史',
        'clear_history': '清除历史',
        'encryption': '加密',
        'encrypt_qr': '加密二维码',
        'decrypt_qr': '解密二维码',
        'warning': '警告',
        'success': '成功',
        'info': '信息',
        'yes': '是',
        'no': '否',
        'enter_password': '输入密码',
        'encrypt_title': '加密二维码',
        'encrypt_password': '输入加密密码',
        'encrypt_success': '二维码加密成功',
        'decrypt_title': '解密二维码',
        'decrypt_password': '输入解密密码',
        'decrypt_success': '二维码解密成功',
        'temp_qr_info': '二维码将在{minutes}分钟内有效',
        'history_title': '二维码历史记录',
        'history_text': '文本',
        'history_type': '类型',
        'history_created': '创建时间',
        'history_expires': '过期时间',
        'history_encrypted': '加密状态',
        'history_permanent': '永久',
        'history_clear_confirm': '确定要清除历史记录吗？',
        'history_cleared': '历史记录已清除',
        'wifi_title': 'Wi-Fi二维码',
        'wifi_ssid': '网络名称(SSID)',
        'wifi_password': '密码',
        'wifi_error': '请输入网络名称和密码',
        'location_title': '位置二维码',
        'location_lat': '纬度',
        'location_lon': '经度',
        'location_error': '请输入有效坐标'
    }
}